export const GET_TODO_REQUEST = "GET_TODO_REQUEST"
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS"
export const GET_TODO_FAIL = "GET_TODO_FAIL"
export const POST_TODO_SUCCESS = "POST_TODO_SUCCESS"



